spring:
  application:
    name: ai-service
  profiles:
    active: prod
  cloud:
    nacos:
      username: nacos
      password: ivKmx77J5vYcb53N
      server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*Mapper.xml

server:
  port: 8184

tess4j:
  tesseract:
    datapath: ./tessdata







